from textwrap import dedent

import pytest

from solutions.day08 import solve


@pytest.fixture
def example_data():
    return dedent("""
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """
                  )


def test_example_data(example_data: str):
    assert solve(example_data) == (14, 34)
